### PR TITLE
Sgratzl/improvements

### LINKED ISSUE #21: Website Previews shows the forked version on different media
works in slack, but not on Facebook for example.

### LINKED ISSUE #34: title page
maximize height of first section to 100vh

### LINKED ISSUE #35: add anchor for tdp, dTiles and Ordino for better linking

### PR DESCRIPTION
**Pull request by sgratzl**
* fix #35 
 * fix #21
 * fix #34 
 * center banner text in the middle (responsive)
 * jump to jobs description
 * all favicons
 * proper social media links
 * progressive thumbnails for the preview + unify thumbnails (full hd is enough)
 * remove superfluous fonts

### CODE REVIEW

**Review by mstreit — COMMENTED** [review]
looks great!

**Review by mstreit — APPROVED** [review]

**Review by lehnerchristian — COMMENTED** [review]
good improvements, 2 questions:
- I think the content should also jump to the job description if the user clicks on a job? e.g. on `Senior Full Stack Developer`, otherwise the big banner is shown at first and the user needs to scroll down
- should we provide a link icon next to our product headlines to provide the possibility to copy the anchor and forward it to somebody (use case: somebody stumbles upon our website, discovers dTiles and wants to send the link to exactly this product to his / her manager)

**Comment by sgratzl** [comment]
> I think the content should also jump to the job description if the user clicks on a job? e.g. on Senior Full Stack Developer, otherwise the big banner is shown at first and the user needs to scroll down

just add the `#jobs´, please



> should we provide a link icon next to our product headlines to provide the possibility to copy the anchor and forward it to somebody (use case: somebody stumbles upon our website, discovers dTiles and wants to send the link to exactly this product to his / her manager)

the anchors are more for internal use, like in about pages. The content is too short such that a real anchor for the user is useful

**Comment by lehnerchristian** [comment]
added a job anchor
job_anchor

**Review by lehnerchristian — APPROVED** [review]

**Comment by mstreit** [comment]
@lehnerchristian @stefan, you can also update job description to 'Product Owner & Full Stack Dev' if you want

**Comment by sluger** [comment]
i think this is too much to list all roles. i rather would prefer a broader and more simple term like Software Engineer.

**Comment by sgratzl** [comment]
why is this discussion part of this PR again?

**Pull request merged**
